"""Add emal, name, hashed_password, created_at field to users table

Revision ID: e714493d5eec
Revises: 1adfc8f3e9b6
Create Date: 2025-12-25 11:27:03.163741

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e714493d5eec"
down_revision: Union[str, Sequence[str], None] = "1adfc8f3e9b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("email", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "users", sa.Column("name", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "users", sa.Column("hashed_password", sa.String(), nullable=False)
    )
    op.add_column(
        "users",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.drop_constraint(op.f("uq_users_username"), "users", type_="unique")
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "username", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.create_unique_constraint(
        op.f("uq_users_username"),
        "users",
        ["username"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("users", "created_at")
    op.drop_column("users", "hashed_password")
    op.drop_column("users", "name")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
